[package]
name = "rust-gen-url"
version = "0.1.0"
authors = ["Nattapon Pondongnok <nainatjab999@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
